evaluate:
  gt_dataset_config_file: /home/kudo/code/config/dense_correspondence/evaluation/kitti_whole.yaml
  model_lst:
  - experiments/exp_08202020-152733/trained_models/kitti_whole_3
  - experiments/exp_08202020-155210/trained_models/kitti_left_3
  - experiments/exp_08202020-161940/trained_models/kitti_right_3
  num_image_pairs: 100
  required: false
experiments:
  as_experiment: true
generate_dataset:
  data_source: ../data/pdc
  ext: png
  generate_depth: true
  image_dir: null
  meta_dir: null
  model_path: ../data/pdc/depth_models/weights_199
  no_cuda: false
  original_data: logs_proto_original
  output_dir: null
  output_target: rendered_images
  pose_data_path: ../data/pdc/poses
  replace_poses: false
  required: false
  scaling_method: default_scaling
  zero_masked: false
train:
  dataset: logs_proto_kitti_raw
  dataset_config_file: /home/kudo/code/config/kitti/kitti.yaml
  dimension: 3
  logging_dir: trained_models/new_new_test_caterpillar/
  num_iterations: 374
  required: true
  train_config_file: /home/kudo/code/config/dense_correspondence/training/training.yaml
