logs_root_path: logs_proto_kitti_right 
object_id: "kitti"
train:
- "0"
- "1"
- "2"
- "3"
- "4"
- "5"
- "6"
- "7"
test:
- "8"
- "9"
- "10"
shape:
  image_width: 1241
  image_height: 376
# evaluation_labeled_data_path: 
# - "evaluation_labeled_data/caterpillar_cross_scene_labels.yaml"